---
# Variables here are applicable to hosts in the "osds" group NOT the "osd" role
#
# You can override them at the host or group level.

###########
# GENERAL #
###########

# Even though OSD nodes should not have the admin key at their disposal,
# some people might want to have it distributed on OSD nodes.
# Setting 'copy_admin_key' to 'true' will copy the admin key to the /etc/ceph/ directory.
copy_admin_key: false

##############
# CEPH OPTIONS
##############

# Devices to be used as OSDs.
#
# You can pre-provision disks that are not present yet; Ansible will just skip them.
# Newly added disks will be automatically configured during the next run.

devices:
  - /dev/sdb

# Co-locate both journal and data on the same disk, creating a partition at the beginning of the device.
journal_collocation: true
