- hosts: all
  tags:
    - init
  tasks:
    - name: Set host name
      command: hostnamectl set-hostname {{ inventory_hostname }}
    - name: Persist host name
      sudo: yes
      copy:
        dest: /etc/hostname
        content: "{{ inventory_hostname }}"
        force: yes
        owner: root
        group: root
        mode: 0644
    - name: Enable local host name resolution
      sudo: yes
      lineinfile:
        dest: /etc/hosts
        line: "{{ primary_ipv4 }} {{ inventory_hostname }}"
        present: yes
