- hosts: all
  tags:
    - init
  tasks:
    - name: Set host name
      command: hostnamectl set-hostname {{ inventory_hostname }}
    - name: Persist host name
      sudo: yes
      copy:
        dest: /etc/hostname
        content: "{{ inventory_hostname }}"
        force: yes
        owner: root
        group: root
        mode: 0644

