- hosts: all
  tags:
    - init
  tasks:
    - name: Set host name
      command: hostnamectl set-hostname {{ inventory_hostname }}
    - name: Persist host name
      sudo: yes
      copy:
        dest: /etc/hostname
        content: "{{ inventory_hostname }}"
        force: yes
        owner: root
        group: root
        mode: 0644
    - name: Ensure host names for all nodes are resolvable
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item]['private_ipv4'] }} {{ item }}"
        state: present
      with_items: groups['all']
